name: env
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - snakemake-minimal=7.19.1
    - r-base=4.2.2
    - bcftools=1.8
    - samtools=1.6
    - minimap2=2.24
    - curl
